import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from "./_components/Footer";
import "./globals.css";
import AuthProvider from "./_providers/auth";
import { Toaster } from "./_components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark" style={{ colorScheme: "dark" }}>
      <meta name="robots" content="noindex, nofollow" />
      <link rel="icon" type="image/x-icon" href="/favicon.ico"></link>
      <body className="bg-background text-foreground antialiased">
        <AuthProvider>
          {children}
          {/* FOOTER */}
          <Toaster />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
